import React, { Fragment } from 'react';

const htmlTag = {
  '<!--': '<!--',
  '!DOCTYPE': '!DOCTYPE',
  a: 'a',
  abbr: 'abbr',
  acronym: 'acronym',
  address: 'address',
  applet: 'applet',
  area: 'area',
  article: 'article',
  aside: 'aside',
  audio: 'audio',
  b: 'b',
  base: 'base',
  basefont: 'basefont',
  bdo: 'bdo',
  big: 'big',
  blockquote: 'blockquote',
  body: 'body',
  br: 'br',
  button: 'button',
  canvas: 'canvas',
  caption: 'caption',
  center: 'center',
  cite: 'cite',
  code: 'code',
  col: 'col',
  colgroup: 'colgroup',
  datalist: 'datalist',
  dd: 'dd',
  del: 'del',
  dfn: 'dfn',
  div: 'div',
  dl: 'dl',
  dt: 'dt',
  em: 'em',
  embed: 'embed',
  fieldset: 'fieldset',
  figcaption: 'figcaption',
  figure: 'figure',
  font: 'font',
  footer: 'footer',
  form: 'form',
  frame: 'frame',
  frameset: 'frameset',
  head: 'head',
  header: 'header',
  h1: 'h1',
  h2: 'h2',
  h3: 'h3',
  h4: 'h4',
  h5: 'h5',
  h6: 'h6',
  hr: 'hr',
  html: 'html',
  i: 'i',
  iframe: 'iframe',
  img: 'img',
  input: 'input',
  ins: 'ins',
  kbd: 'kbd',
  label: 'label',
  legend: 'legend',
  li: 'li',
  link: 'link',
  main: 'main',
  map: 'map',
  mark: 'mark',
  meta: 'meta',
  meter: 'meter',
  nav: 'nav',
  noscript: 'noscript',
  object: 'object',
  ol: 'ol',
  optgroup: 'optgroup',
  option: 'option',
  p: 'p',
  param: 'param',
  pre: 'pre',
  progress: 'progress',
  q: 'q',
  s: 's',
  samp: 'samp',
  script: 'script',
  section: 'section',
  select: 'select',
  small: 'small',
  source: 'source',
  span: 'span',
  strike: 'strike',
  strong: 'strong',
  style: 'style',
  sub: 'sub',
  sup: 'sup',
  table: 'table',
  tbody: 'tbody',
  td: 'td',
  textarea: 'textarea',
  tfoot: 'tfoot',
  th: 'th',
  thead: 'thead',
  time: 'time',
  title: 'title',
  tr: 'tr',
  u: 'u',
  ul: 'ul',
  var: 'var',
  video: 'video',
  wbr: 'wbr',
};

const componentsLibrary = {
  Card: React.lazy(() => import('components/Card/Card')),
  CardWrapper: React.lazy(() => import('components/Card/CardWrapper')),
  Fragment: ({ children }) => <Fragment>{children}</Fragment>,
  ...htmlTag,
};

export default componentsLibrary;
